export const STATUS_SPIN = 'STATUS_SPIN';
export const TOGGLE_STATUS_SPIN = 'TOGGLE_STATUS_SPIN';
export const IMAGES_POST = 'IMAGES_POST';
export const POSTS = 'POSTS';
export const POST = 'POST';
export const TOGGLE_STATUS_PRESENTIAL_MODAL = 'TOGGLE_STATUS_PRESENTIAL_MODAL';
export const STATUS_PRESENTIAL_MODAL = 'STATUS_PRESENTIAL_MODAL';
